image: quantumtinkerer/research

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install asv scikit-optimize
  - pip install -r test-requirements.txt
  - asv machine --config=benchmarks/asv.conf.json --yes

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - py.test --verbose --cov=adaptive --cov-report term --cov-report html adaptive
  artifacts:
    paths:
      - htmlcov

mirror repository:
  allow_failure: true
  variables:
    REPO: "git@github.com:python-adaptive/adaptive.git"
  before_script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  after_script:
    - rm -rf ~/.ssh
  script:
    - ORIGIN_URL=$(git config --get remote.origin.url)
    - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
    - git push --mirror $REPO

benchmarks for master:
  stage: test
  script:
    - asv run --config=benchmarks/asv.conf.json --skip-existing-commits ALL 
  artifacts:
    paths:
      - benchmarks/results
      - benchmarks/env
    expire_in: 7d
  only:
    - master

benchmarks not master:
  stage: test
  script:
    - asv run --config=benchmarks/asv.conf.json master..${CI_COMMIT_REF_NAME}
  except:
    - master

upload benchmarks:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - asv publish
    - "rsync -ravz --delete benchmarks/html/* adaptive-asv@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh
