image: quantumtinkerer/research

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r test-requirements.txt
    - conda install -y -q scikit-optimize
    - py.test --verbose --cov=adaptive --cov-report term --cov-report html adaptive
  artifacts:
    paths:
      - htmlcov

mirror repository:
  allow_failure: true
  variables:
    REPO: "git@github.com:python-adaptive/adaptive.git"
  before_script:
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  after_script:
    - rm -rf ~/.ssh
  script:
    - ORIGIN_URL=$(git config --get remote.origin.url)
    - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
    - git push --mirror $REPO

benchmarks for master:
  stage: test
  script:
    - pip install https://github.com/airspeed-velocity/asv/archive/master.zip  # we need github.com/airspeed-velocity/asv/pull/540 which is not in the latest release
    - cd benchmarks
    - asv machine --yes
    - asv run --skip-existing-commits ALL 
  artifacts:
    paths:
      - benchmarks/results
      - benchmarks/env
    expire_in: 7d

benchmarks not master:
  stage: test
  script:
    - asv run ${CI_COMMIT_REF_NAME}{u}..master
  except:
    - master

upload_benchmarks:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - asv publish
    - "rsync -ravz --delete benchmarks/html/* adaptive-asv@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh
